# Generated by Django 4.2.10 on 2024-02-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='Enter_at_least_one_number',
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('work_phone__isnull', False), ('personal_phone__isnull', True)), models.Q(('work_phone__isnull', True), ('personal_phone__isnull', False)), models.Q(('work_phone__isnull', False), ('personal_phone__isnull', False)), _connector='OR'), name='Enter_at_least_one_number'),
        ),
    ]
