# Generated by Django 4.2.10 on 2024-02-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_person_enter_at_least_one_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='Enter_at_least_one_number',
        ),
    ]
