# Generated by Django 4.2.10 on 2024-02-15 18:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_person_enter_at_least_one_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='work_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Рабочий телефон'),
        ),
    ]
